# Generated by Django 3.2.9 on 2021-12-03 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdb',
            old_name='visit_date',
            new_name='VisitDate',
        ),
        migrations.AddField(
            model_name='patientdb',
            name='json_path',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientdb',
            name='patient_id',
            field=models.TextField(),
        ),
    ]
