# Generated by Django 3.2.9 on 2021-12-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20211203_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdb',
            name='patient_id',
            field=models.CharField(max_length=50),
        ),
    ]
