# Generated by Django 3.2.9 on 2021-12-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_patientdb_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdb',
            old_name='VisitDate',
            new_name='visit_date',
        ),
    ]
