# Generated by Django 4.0 on 2022-01-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_patientdb_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdb',
            name='fk',
        ),
        migrations.AddField(
            model_name='patientdb',
            name='comment',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
