# Generated by Django 4.0 on 2022-02-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0008_delete_mymodel'),
        ('history', '0013_remove_patientdb_fk_patientdb_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdb',
            name='comment',
            field=models.ForeignKey(db_column='comment', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='IO.board'),
        ),
    ]
