# Generated by Django 4.0 on 2022-02-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0014_alter_patientdb_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdb',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
