# Generated by Django 4.0 on 2022-02-15 00:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0016_alter_patientdb_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='history.patientdb')),
            ],
        ),
    ]
