# Generated by Django 4.0 on 2022-02-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0019_alter_ment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ment',
            name='body',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
