# Generated by Django 4.0 on 2022-02-22 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0022_patientdb_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdb',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='Tagging', to=settings.AUTH_USER_MODEL),
        ),
    ]
