# Generated by Django 4.0 on 2022-02-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0027_ment_interpretation_alter_ment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ment',
            name='body',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
