# Generated by Django 4.0 on 2022-03-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0028_alter_ment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ment',
            name='interpretation',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
