# Generated by Django 4.0 on 2022-03-02 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0030_interpretations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretations',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pandok', to='history.patientdb'),
        ),
    ]
