# Generated by Django 4.0 on 2022-03-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0031_alter_interpretations_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interpretations',
        ),
    ]
