# Generated by Django 4.0 on 2022-03-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0033_notagging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdb',
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Notagging',
        ),
    ]
