# Generated by Django 4.0 on 2022-03-02 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('history', '0034_remove_patientdb_tags_delete_notagging'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdb',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='Tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notagging',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Vote', models.BooleanField(db_column='후보', default=False)),
                ('NoTag', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
            ],
        ),
    ]
