# Generated by Django 4.0 on 2022-03-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0035_patientdb_tags_notagging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ment',
            name='body',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ment',
            name='interpretation',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
