# Generated by Django 4.0 on 2022-03-04 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0040_alter_ment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdb',
            name='Tags_defalut',
            field=models.ManyToManyField(blank=True, related_name='Tags2', to=settings.AUTH_USER_MODEL),
        ),
    ]
