# Generated by Django 4.0 on 2022-03-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0041_patientdb_tags_defalut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdb',
            old_name='Tags_defalut',
            new_name='Tags_default',
        ),
    ]
