# Generated by Django 4.0 on 2022-04-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0046_tagging_tag1_tagging_tags_default1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notagging',
        ),
    ]
