# Generated by Django 4.0 on 2022-04-07 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('history', '0047_delete_notagging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging',
            name='Tag1',
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='Tags_default1',
        ),
        migrations.CreateModel(
            name='Tagging1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Vote', models.BooleanField(db_column='후보', default=False)),
                ('Tag1', models.ManyToManyField(blank=True, related_name='likes1', to=settings.AUTH_USER_MODEL)),
                ('Tags_default1', models.ManyToManyField(blank=True, related_name='dislike1', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
            ],
        ),
    ]
