# Generated by Django 4.0 on 2022-04-19 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0048_remove_tagging_tag1_remove_tagging_tags_default1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagging3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Vote', models.BooleanField(db_column='후보', default=False)),
                ('Tag3', models.ManyToManyField(blank=True, related_name='likes3', to=settings.AUTH_USER_MODEL)),
                ('Tags_default3', models.ManyToManyField(blank=True, related_name='dislike3', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tagging2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Vote', models.BooleanField(db_column='후보', default=False)),
                ('Tag2', models.ManyToManyField(blank=True, related_name='likes2', to=settings.AUTH_USER_MODEL)),
                ('Tags_default2', models.ManyToManyField(blank=True, related_name='dislike2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
            ],
        ),
    ]
