# Generated by Django 4.0 on 2022-04-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0050_remove_patientdb_tags4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdb',
            name='json_path_sagittal',
            field=models.TextField(default='', null=True),
        ),
    ]
