# Generated by Django 4.0 on 2022-11-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0051_patientdb_json_path_sagittal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging',
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='Tags_default',
        ),
    ]
