# Generated by Django 4.0 on 2022-11-21 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0052_remove_tagging_tag_remove_tagging_tags_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging1',
            name='Tag1',
        ),
        migrations.RemoveField(
            model_name='tagging1',
            name='Tags_default1',
        ),
        migrations.RemoveField(
            model_name='tagging2',
            name='Tag2',
        ),
        migrations.RemoveField(
            model_name='tagging2',
            name='Tags_default2',
        ),
        migrations.RemoveField(
            model_name='tagging3',
            name='Tag3',
        ),
        migrations.RemoveField(
            model_name='tagging3',
            name='Tags_default3',
        ),
    ]
