# Generated by Django 4.0 on 2022-11-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('history', '0053_remove_tagging1_tag1_remove_tagging1_tags_default1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagging',
            new_name='Nodule',
        ),
        migrations.RenameModel(
            old_name='Tagging3',
            new_name='Nodule1',
        ),
        migrations.RenameModel(
            old_name='Tagging2',
            new_name='Nodule2',
        ),
        migrations.RenameModel(
            old_name='Tagging1',
            new_name='Nodule3',
        ),
    ]
