# Generated by Django 4.0 on 2022-11-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0054_rename_tagging_nodule_rename_tagging3_nodule1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodule',
            name='Vote',
            field=models.BooleanField(db_column='결절_1', default=False),
        ),
        migrations.AlterField(
            model_name='nodule1',
            name='Vote',
            field=models.BooleanField(db_column='결절_2', default=False),
        ),
        migrations.AlterField(
            model_name='nodule2',
            name='Vote',
            field=models.BooleanField(db_column='결절_3', default=False),
        ),
        migrations.AlterField(
            model_name='nodule3',
            name='Vote',
            field=models.BooleanField(db_column='결절_4', default=False),
        ),
    ]
