# Generated by Django 4.0 on 2022-11-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0055_alter_nodule_vote_alter_nodule1_vote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdb',
            name='comment',
        ),
    ]
