# Generated by Django 3.2.9 on 2021-12-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='{patient_id}/%Y/%m/%d'),
        ),
    ]
