# Generated by Django 3.2.9 on 2021-12-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0002_alter_board_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/%Y/%m/%d'),
        ),
    ]
