# Generated by Django 4.0 on 2021-12-30 03:39

import IO.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0004_alter_board_imgfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
            ],
        ),
    ]
