# Generated by Django 4.0 on 2022-01-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0005_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
