# Generated by Django 4.0 on 2022-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0006_alter_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
