# Generated by Django 4.0 on 2022-01-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0007_alter_board_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
