# Generated by Django 4.0 on 2022-03-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0010_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
