# Generated by Django 4.0 on 2022-03-23 05:13

import IO.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0011_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to=IO.utils.image_upload_path)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IO.board')),
            ],
        ),
    ]
