# Generated by Django 4.0 on 2022-03-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0012_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='imgfile',
        ),
    ]
