# Generated by Django 4.0 on 2022-03-23 05:54

import IO.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0013_remove_board_imgfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=IO.utils.image_upload_path),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
