# Generated by Django 4.0 on 2022-04-22 01:57

import IO.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0014_board_imgfile_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='imgfile2',
            field=models.ImageField(blank=True, null=True, upload_to=IO.utils.image_upload_path),
        ),
    ]
