# Generated by Django 4.0 on 2022-04-25 01:48

import IO.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO', '0015_board_imgfile2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='imgfile2',
            field=models.ImageField(blank=True, null=True, upload_to=IO.utils.image_upload_path2),
        ),
    ]
